config/routes.rb
Rails.application.routes.draw do

  get 'notifications/link_through'

  resources :likes, only:[:create, :destroy]
  devise_for :users, :controllers => {:registrations=> "registrations"}
  resources :posts do
    resources :comments
  end

  resources :relationships, only:[:create, :destroy]
  # root 'posts#index'
  root 'pages#index'
  
  get '/posts/hashtag/:name', to:'posts#hashtags'
  get 'search' => 'pages#search'
  get '/about' => 'pages#about'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'notifications', to: 'notifications#list'
  get 'notifications/:id/link_through', to:'notifications#link_through', as: :link_through
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    after_action :create_notifications, only:[:create]

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.build(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            render :index
        end
    end
    
    def destroy
        @comment = Comment.find(params[:id])
        if @comment.destroy
            render :index
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:post_id, :user_id, :body)
    end

    def create_notifications
        return if @post.user.id == current_user.id
        Notification.create(user_id: @post.user.id, notified_by_id: current_user.id, post_id: @post.id, notified_type:"コメント")
    end
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment] ) do |form| %>
  <div class="commentFormWrap">
    <%= form.text_area :body, class:"commentForm", placeholder:"筋トレ、ダイエットをしているユーザーに応援コメントをしましょう！" %>
  </div>
  <div class="actions">
    <%= form.submit "コメントをする", class:"commentFormSubmit" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<div class="commentList">
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <div class="comment">
        <p class="commentName">@<%= link_to "#{comment.user.username}", user_path(comment.user.id), class:"commentNameLink" %></p>
        <p class="commentBody"><%= comment.body %></p>
        <% if comment.user == current_user %>
          <p class="commentDeleteWrap"><%= link_to '削除', post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class:"commentDelete" %></p>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('')