config/routes.rb
Rails.application.routes.draw do

  get 'notifications/link_through'

  resources :likes, only:[:create, :destroy]
  devise_for :users, :controllers => {:registrations=> "registrations"}
  resources :posts do
    resources :comments
  end

  resources :relationships, only:[:create, :destroy]
  # root 'posts#index'
  root 'pages#index'
  
  get '/posts/hashtag/:name', to:'posts#hashtags'
  get 'search' => 'pages#search'
  get '/about' => 'pages#about'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'notifications', to: 'notifications#list'
  get 'notifications/:id/link_through', to:'notifications#link_through', as: :link_through
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates_uniqueness_of :username, format: {with: /^[a-zA-Z0-9]+$/}
  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # current_passwordなしで更新
  attr_accessor :current_password

  has_many :comments, dependent: :destroy
  
  mount_uploader :avatar, ImageUploader
         
  has_many :posts, :dependent=>:destroy
  has_many :active_relationships, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  has_many :passive_relationships, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy
  
  has_many :following, through: :active_relationships, source: :followed #followedsは英語的におかしいので、source: :followedと明示的に別記する。
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :likes, dependent: :destroy

  has_many :notifications, dependent: :destroy

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    clean_up_passwords
    update_attributes(params, *options)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, except:[:show, :index]
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
    :following, :followers]

    def show
        @user = User.find(params[:id])
        @posts = @user.posts.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 21)
        # @posts = Post.order("created_at DESC").paginate(:page => params[:page], :per_page => 21)
    end

    def following
        @title = "フォロー中"
        @user = User.find(params[:id])
        @users = @user.following
        render 'show_follow' #actionに対応するビューを呼び出すが、明示的にshow_followと記述し、show_followビューを表示させる
    end

    def followers
        @title = "フォロワー"
        @user = User.find(params[:id])
        @users = @user.followers
        render 'show_follow'
    end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "フォローする", class:"followForm" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
<%= f.submit "フォロー解除", class:"unfollowForm" %>
<% end %>

app/views/users/show.html.erb
<% @user ||= current_user %>
<div class="profileWrap container">
    <% if user_signed_in? %>
        <% unless current_user?(@user) %>
        <div id="follow_form" class="followFormPosition">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <% else %>
            <%= render 'follow' %>
        <% end %>
        </div>
        <% end %>    
    <% end %>
    <div class="profileHeader">
        <div class="profileHeaderLeft">
            <div class="profileImage">
                <% if  @user.avatar.present? %>
                    <%= image_tag @user.avatar.to_s, class:"profileAvatar" %>
                <% else %>
                    <i class="fas fa-user"></i>
                <% end %>
            </div>
        </div>
        <div class="profileHeaderRight">
            <div class="profileNumWrap">
                <div class="profileNumLeft">
                    <div class="profileNumTitle">フォロー中</div>
                    <%= link_to following_user_path(@user) do %>
                        <div class="profileNum" id="following"><%= @user.following.count %></div>
                    <% end %>
                </div>
                <div class="profileNumCenter">
                    <div class="profileNumTitle">フォロワー</div>
                    <%= link_to followers_user_path(@user) do %>
                        <div class="profileNum" id="followers"><%= @user.followers.count %></div>
                    <% end %>
                </div>
                <div class="profileNumRight">
                    <div class="profileNumTitle">投稿数</div>
                    <div class="profileNum"><%= @user.posts.count %></div>
                </div>
            </div>
            <% if user_signed_in? && current_user.id == @user.id %>
                <p class="profileEdit">
                    <%= link_to "プロフィール編集", edit_user_registration_path, class:"profileFormButton" %>
                </p>
            <% end %>
        </div>
    </div>
    <div class="profileBottom">
        <p class="profileName"><%= @user.name %></p>
        <p class="profileText"><%= @user.introduce %></p>
        <div id="calendar"></div>
        <p style="font-size:12px;">※トレーニングをして、写真を撮った日はカレンダーの色が変わります</p>
    </div>
</div>

<div class="squarePostList container" id="usersShow">
    <%= render @posts %>
</div>
<%= will_paginate @posts %>

<script>
$(function(){
    var user_id = <%= @user.id %>
    $('#calendar').fullCalendar({
        displayEventTime:false,
        displayEventTitle:true,
        events: `/users/${user_id}.json`,
        eventRender:function(event, element){
            var dataToFind = moment(event.start).format('YYYY-MM-DD');
            $("td[data-date='"+dataToFind+"']").addClass('activeDay');
        }
     });
})
</script>

app/views/users/show.js.erb
$("#usersShow").append("<%= escape_javascript render(@posts) %>");
$(".pagination").replaceWith("<%= escape_javascript will_paginate(@posts) %>");

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="relationshipWrap container">
<h3><%= @title %></h3>
<% if @users.any? %>
    <div class="users follow">
            <% @users.each do |user| %>
            <div class="relationshipItem">
                <%= link_to user do %>
                    <% if  user.avatar.present? %>
                        <div class="relationshipItemImage">
                            <%= image_tag user.avatar.to_s, class:"icon" %>
                        </div>
                    <% else %>
                        <div class="relationshipItemImage">
                            <i class="fas fa-user"></i>
                        </div>
                    <% end %>
                <% end %>
                <div class="relationshipItemName">
                    <%= user.name %>
                </div>
                <div class="relationshipItemRight">
                    <% unless current_user?(@user) %>
                        <div id="follow_form" class="relationshipButton">
                    <% if current_user.following?(@user) %>
                        <%= render 'unfollow' %>
                    <% else %>
                        <%= render 'follow' %>
                    <% end %>
                        </div>
                    <% end %>
                </div>
                
            </div>
            <% end %>
    </div>
<% else %>
    <p>まだ<%= @title %>はいません。</p>
<% end %>
</div>