config/routes.rb
Rails.application.routes.draw do

  get 'notifications/link_through'

  resources :likes, only:[:create, :destroy]
  devise_for :users, :controllers => {:registrations=> "registrations"}
  resources :posts do
    resources :comments
  end

  resources :relationships, only:[:create, :destroy]
  # root 'posts#index'
  root 'pages#index'
  
  get '/posts/hashtag/:name', to:'posts#hashtags'
  get 'search' => 'pages#search'
  get '/about' => 'pages#about'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'notifications', to: 'notifications#list'
  get 'notifications/:id/link_through', to:'notifications#link_through', as: :link_through
end

app/views/pages/about.html.erb
<div class="fixContainer">
    <h2>このサイトについて</h2>
    <p>このサイトはビギナー筋トレSNSです。 <br><br>
    インスタグラムなどのSNSに自分が運動したり,<br>
    筋トレした姿をアップしている人が増えていますよね。<br><br>
    でも、初めてばかりの人や普段からSNSに自撮りをあげていない人からすると<br>インスタ自撮りはちょっと抵抗があるように感じます。<br><br>
    そこで、運動をし始めた人、三日坊主で運動が終わってしまう人のために毎日ちょっとでも運動ができるようなサービスを作りました。</p>
</div>

app/views/pages/home.html.erb
<div class="tab">
    <%= link_to root_path, class:"tabLeft-active" do %>
        <div>新着</div>
    <% end %>
    <%= link_to posts_path, class:"tabRight" do %>
        <div>フォロー中</div>
    <% end %>
</div>
<br>
<div class="newPostList">
    <% @posts.each do |post| %>
    <div class="newPostItem">
        <% if !post.image.blank? %>
            <%= link_to(post, class:"newPostLink") do %><!-- プレビューさせる -->
                <%= image_tag(post.image.url, class:"newPostImage")%>
            <% end %>
        <% end %>
    </div>
    <% end %>
</div>

app/views/pages/index.html.erb
    <div class="tabWrap">
        <div class="tab container">
            <%= link_to root_path, class:"tabLeft-active" do %>
                <div>新着</div>
            <% end %>
            <%= link_to posts_path, class:"tabRight" do %>
                <div>フォロー中</div>
            <% end %>
        </div>
    </div>
    <br>

    <div class="squarePostList container" id="pagesIndex">
        <%= render @posts %>
    </div>
    <%= will_paginate @posts %>

app/views/pages/index.js.erb
$('#pagesIndex').append('<%= escape_javascript render(@posts) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@posts) %>');

app/views/pages/search.html.erb
<%= form_tag search_path, :method => 'get', class:"container" do %>
    <div>
        <%= text_field_tag :search, nil, placeholder:"検索", class:"searchForm" %>
    </div>
    <div>
        <%= submit_tag '検索', :name => nil, class:"searchSubmit" %>
    </div>
<% end %>

<div class="squarePostList container" id="pagesSearch">
    <%= render @posts %>
</div>
<%= will_paginate @posts %>

app/views/pages/search.js.erb
$("#pagesSearch").append('<%= escape_javascript render(@posts) %>');
$(".pagination").replaceWith('<%= escape_javascript will_paginate(@posts) %>');