config/routes.rb
Rails.application.routes.draw do

  get 'notifications/link_through'

  resources :likes, only:[:create, :destroy]
  devise_for :users, :controllers => {:registrations=> "registrations"}
  resources :posts do
    resources :comments
  end

  resources :relationships, only:[:create, :destroy]
  # root 'posts#index'
  root 'pages#index'
  
  get '/posts/hashtag/:name', to:'posts#hashtags'
  get 'search' => 'pages#search'
  get '/about' => 'pages#about'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'notifications', to: 'notifications#list'
  get 'notifications/:id/link_through', to:'notifications#link_through', as: :link_through
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PROUDEE</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
  </head>

  <body>
    <!-- ヘッダー部分 -->
    <div class="header">
      <div class="container">    
        <div class="headerLeft">
          <p><%= link_to 'About', about_path, class:"welcomeLetter" %></p>
        </div>
        <div class="headerCenter">
          <div class="title">
            <%= link_to root_path, class:"titleNameLink" do %>
              <h1 class="titleName">PROUDEE</h1>
            <% end %>
          </div>
        </div>
        <div class="headerRight">
          <% if user_signed_in? %>
            <p class="headerRightLogoutWrap">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"headerRightLogout" %>
            </p>
            
          <% else %>
              <button class="headerRightLoginWrap">
                <%= link_to "ログイン", new_user_session_path, class:"headerRightLogin" %>
              </button>
              <button class="headerRightRegWrap">
                <%= link_to "登録", new_user_registration_path, class:"headerRightReg" %>
              </button>
          <% end %>
        </div>
      </div>
      <!-- flashメッセージ -->
      <% unless flash.empty? %>
        <script type="text/javascript">
          <% flash.each do |key, value| %>
            <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
            toastr['<%= type %>']('<%= value %>');
          <% end %>
        </script>
      <% end %>
    </div>
      <%= yield %>
    <div class="footer">
      <div class="footerElement container">
        <div class="home">
          <%= link_to root_path do %>
            <i class="fas fa-home <%= controller.action_name == 'index' ? 'active': 'inactive'%>"></i>
          <% end %>
        </div>
        <div class="search">
          <%= link_to search_path do %>
            <i class="fas fa-search <%= controller.action_name == 'search' ? 'active': 'inactive'%>"></i>
          <% end %>
        </div>
        <div class="post">
            <%= link_to new_post_path do %>
              <i class="fas fa-plus-square  <%= controller.action_name == 'new' ? 'active': 'inactive'%>""></i>
            <% end %>
        </div>
        <div class="notice">
          <%= link_to notifications_path do %>
            <% if user_signed_in? &&  current_user.notifications.where(read: false).count != 0 %>
              <span class="noticeCount"><%= current_user.notifications.where(read: false).count %></span>
            <% end %>
            <i class="fas fa-bell <%= controller.action_name == 'list' ? 'active': 'inactive'%>"></i>
          <% end %>
        </div>
        <div class="profile">
          <% if user_signed_in? %>
            <%= link_to user_path(current_user) do %>
              <i class="fas fa-user <%= controller.action_name == 'show' ? 'active': 'inactive'%>"></i>
            <% end %>
          <% else %>
            <%= link_to new_user_registration_path do %>
            <i class="fas fa-user <%= controller.action_name == 'show' ? 'active': 'inactive'%>"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>